### === Role ===

### Get all role
GET http://localhost:3000/role/obtain HTTP/1.1

### Get single role
GET http://localhost:3000/role/obtain?_id=something HTTP/1.1

### Add a role
POST http://localhost:3000/role/create HTTP/1.1
content-type: application/json

{
    "name": "Test",
    "description": "This is a test role."
}

### Modify a role
PUT http://localhost:3000/role/modify?_id=something HTTP/1.1
content-type: application/json

{
    "name": "Test Renamed"
}

### Delete a role
DELETE http://localhost:3000/role/delete?_id=something HTTP/1.1


### === User ===

### Get all user
GET http://localhost:3000/user/obtain HTTP/1.1

### Get single user
GET http://localhost:3000/user/obtain?_id=something HTTP/1.1

### Add a user
POST http://localhost:3000/user/create HTTP/1.1
content-type: application/json

{
    "username": "Test",
    "authenticationHash": "something",
    "roleId": "some id"
}

### Modify a user
PUT http://localhost:3000/user/modify?_id=something HTTP/1.1
content-type: application/json

{
    "nickname": "Hello World"
}

### Delete a user
DELETE http://localhost:3000/user/delete?_id=something HTTP/1.1